name: JavaScript CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: yarn install, test
        run:
          - yarn install
          - yarn test
        env:
          CI: true
